### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by zomorango** [DelphiWorlds/MoscoExpert#1]
Hi, 
I'm using delphi 10.4.2 I'm trying to submit my app , to do so I'm using Mosco to generate the Assets.car .
In the Delphi IDE at the program options I set all the icons for ipad and iphone. I deploy the app and then use Mosco to update the assets.car but I get errors on the Mosco Message in the mac

2021/06/16 18:20:15.421 Did not find a matching image for: Idiom: iphone, Scale: 2x, Size: 20x20
2021/06/16 18:20:15.444 Did not find a matching image for: Idiom: iphone, Scale: 3x, Size: 20x20
2021/06/16 18:20:15.455 Did not find a matching image for: Idiom: iphone, Scale: 2x, Size: 29x29
2021/06/16 18:20:15.462 Did not find a matching image for: Idiom: iphone, Scale: 3x, Size: 29x29
2021/06/16 18:20:15.464 Did not find a matching image for: Idiom: iphone, Scale: 2x, Size: 40x40
2021/06/16 18:20:15.466 Did not find a matching image for: Idiom: iphone, Scale: 3x, Size: 60x60
2021/06/16 18:20:15.478 Did not find a matching image for: Idiom: ipad, Scale: 2x, Size: 20x20
2021/06/16 18:20:15.483 Did not find a matching image for: Idiom: ipad, Scale: 2x, Size: 29x29
2021/06/16 18:20:15.485 Did not find a matching image for: Idiom: ipad, Scale: 1x, Size: 40x40
2021/06/16 18:20:15.486 Did not find a matching image for: Idiom: ipad, Scale: 2x, Size: 40x40
2021/06/16 18:20:15.489 Did not find a matching image for: Idiom: ipad, Scale: 2x, Size: 83.5x83.5
2021/06/16 18:20:15.493 Did not find a matching image for: Idiom: ios-marketing, Scale: 1x, Size: 1024x1024

Where do I put these images? in the Deploy Window? in a file?

Regards

**Comment by DelphiWorlds** [comment]
If you're using Delphi 10.4.2, you do not need to use Mosco to generate the Assets.car

**Comment by zomorango** [comment]
Hoo... But This is so strange because a couple of days ago I was trying to submit my app to the store using the transport app and I get an error about the icons, that's why I waste 2 days reading workarounds, and after your answer, I try to build the IPA again and this time no errors appear on the transport app.... well sometimes I just don´t get it... now it works... What a waste of time :)

Anyway thanks for pointing me back on the right track, 

regards
José Morango
